// cross-table.js — 192個輪迴交叉中英文對照（《區分的科學》譯名）
// 鍵格式: '角度代碼:個性太陽/個性地球|設計太陽/設計地球'  R=右角度 J=並列 L=左角度
const CROSS_TABLE = {
  'J:1/2|4/49': { zh: '並列交叉之自我表達', en: 'The Juxtaposition Cross of Self-Expression', sign: '天蠍' },
  'J:10/15|18/17': { zh: '並列交叉之行為', en: 'The Juxtaposition Cross of Behavior', sign: '射手 魔羯' },
  'J:11/12|46/25': { zh: '並列交叉之想法', en: 'The Juxtaposition Cross of Ideas', sign: '射手' },
  'J:12/11|25/46': { zh: '並列交叉之發聲*', en: 'The Juxtaposition Cross of Articulation', sign: '雙子' },
  'J:13/7|43/23': { zh: '並列交叉之傾聽', en: 'The Juxtaposition Cross of Listening', sign: '水瓶' },
  'J:14/8|59/55': { zh: '並列交叉之激勵*', en: 'The Juxtaposition Cross of Empowering', sign: '天蠍' },
  'J:15/10|17/18': { zh: '並列交叉之極端', en: 'The Juxtaposition Cross of Extremes', sign: '雙子 巨蟹' },
  'J:16/9|63/64': { zh: '並列交叉之實驗', en: 'The Juxtaposition Cross of Experimentation', sign: '雙子' },
  'J:17/18|38/39': { zh: '並列交叉之意見', en: 'The Juxtaposition Cross of Opinions', sign: '牡羊' },
  'J:18/17|39/38': { zh: '並列交叉之修正', en: 'The Juxtaposition Cross of Correction', sign: '天秤' },
  'J:19/33|1/2': { zh: '並列交叉之需要', en: 'The Juxtaposition Cross of Need', sign: '水瓶' },
  'J:2/1|49/4': { zh: '並列交叉之駕駛*', en: 'The Juxtaposition Cross of the Driver', sign: '金牛' },
  'J:20/34|37/40': { zh: '並列交叉之當下', en: 'The Juxtaposition Cross of the Now', sign: '雙子' },
  'J:21/48|54/53': { zh: '並列交叉之控制', en: 'The Juxtaposition Cross of Control', sign: '牡羊' },
  'J:22/47|11/12': { zh: '並列交叉之優雅', en: 'The Juxtaposition Cross of Grace', sign: '雙魚' },
  'J:23/43|30/29': { zh: '並列交叉之同化', en: 'The Juxtaposition Cross of Assimilation', sign: '金牛' },
  'J:24/44|13/7': { zh: '並列交叉之體悟', en: 'The Juxtaposition Cross of Rationalization', sign: '金牛' },
  'J:25/46|58/52': { zh: '並列交叉之天真', en: 'The Juxtaposition Cross of Innocence', sign: '雙魚 牡羊' },
  'J:26/45|6/36': { zh: '並列交叉之魔術', en: 'The Juxtaposition Cross of the Trickster', sign: '射手' },
  'J:27/28|19/33': { zh: '並列交叉之照顧', en: 'The Juxtaposition Cross of Caring', sign: '金牛' },
  'J:28/27|33/19': { zh: '並列交叉之風險*', en: 'The Juxtaposition Cross of Risks', sign: '天蠍' },
  'J:29/30|20/34': { zh: '並列交叉之承諾', en: 'The Juxtaposition Cross of Commitment', sign: '獅子' },
  'J:3/50|41/31': { zh: '並列交叉之突變', en: 'The Juxtaposition Cross of Mutation', sign: '牡羊 金牛' },
  'J:30/29|34/20': { zh: '並列交叉之命運*', en: 'The Juxtaposition Cross of Fates', sign: '水瓶' },
  'J:31/41|24/44': { zh: '並列交叉之影響', en: 'The Juxtaposition Cross of Influence', sign: '獅子' },
  'J:32/42|56/60': { zh: '並列交叉之保存', en: 'The Juxtaposition Cross of Conservation', sign: '天秤' },
  'J:33/19|2/1': { zh: '並列交叉之隱私*', en: 'The Juxtaposition Cross of Retreat', sign: '獅子' },
  'J:34/20|40/37': { zh: '並列交叉之力量', en: 'The Juxtaposition Cross of Power', sign: '射手' },
  'J:35/5|22/47': { zh: '並列交叉之經驗', en: 'The Juxtaposition Cross of Experience', sign: '雙子' },
  'J:36/6|10/15': { zh: '並列交叉之危機', en: 'The Juxtaposition Cross of Crisis', sign: '雙魚' },
  'J:37/40|5/35': { zh: '並列交叉之交易', en: 'The Juxtaposition Cross of Bargains', sign: '雙魚' },
  'J:38/39|57/51': { zh: '並列交叉之對抗', en: 'The Juxtaposition Cross of Opposition', sign: '魔羯' },
  'J:39/38|51/57': { zh: '並列交叉之挑釁', en: 'The Juxtaposition Cross of Provocation', sign: '巨蟹' },
  'J:4/49|8/14': { zh: '並列交叉之公式', en: 'The Juxtaposition Cross of Formulization', sign: '獅子' },
  'J:40/37|35/5': { zh: '並列交叉之拒絕', en: 'The Juxtaposition Cross of Denial', sign: '處女' },
  'J:41/31|44/24': { zh: '並列交叉之幻想', en: 'The Juxtaposition Cross of Fantasy', sign: '水瓶' },
  'J:42/32|60/56': { zh: '並列交叉之完成', en: 'The Juxtaposition Cross of Completion', sign: '牡羊' },
  'J:43/23|29/30': { zh: '並列交叉之洞見', en: 'The Juxtaposition Cross of Insight', sign: '天蠍' },
  'J:44/24|7/13': { zh: '並列交叉之警覺', en: 'The Juxtaposition Cross of Alertness', sign: '天蠍' },
  'J:45/26|36/6': { zh: '並列交叉之所有權*', en: 'The Juxtaposition Cross of Possession', sign: '雙子' },
  'J:46/25|52/58': { zh: '並列交叉之因緣俱足*', en: 'The Juxtaposition Cross of Serendipity', sign: '處女 天秤' },
  'J:47/22|12/11': { zh: '並列交叉之壓抑', en: 'The Juxtaposition Cross of Oppression', sign: '處女' },
  'J:48/21|53/54': { zh: '並列交叉之深度', en: 'The Juxtaposition Cross of Depth', sign: '天秤' },
  'J:49/4|14/8': { zh: '並列交叉之原則', en: 'The Juxtaposition Cross of Principles', sign: '水瓶' },
  'J:5/35|47/22': { zh: '並列交叉之習慣', en: 'The Juxtaposition Cross of Habits', sign: '射手' },
  'J:50/3|31/41': { zh: '並列交叉之價值', en: 'The Juxtaposition Cross of Values', sign: '天秤 天蠍' },
  'J:51/57|61/62': { zh: '並列交叉之驚嚇*', en: 'The Juxtaposition Cross of Shock', sign: '牡羊' },
  'J:52/58|21/48': { zh: '並列交叉之靜止', en: 'The Juxtaposition Cross of Stillness', sign: '巨蟹' },
  'J:53/54|42/32': { zh: '並列交叉之開始', en: 'The Juxtaposition Cross of Beginnings', sign: '巨蟹' },
  'J:54/53|32/42': { zh: '並列交叉之抱負*', en: 'The Juxtaposition Cross of Ambition', sign: '魔羯' },
  'J:55/59|9/16': { zh: '並列交叉之情緒', en: 'The Juxtaposition Cross of Moods', sign: '雙魚' },
  'J:56/60|27/28': { zh: '並列交叉之刺激', en: 'The Juxtaposition Cross of Stimulation', sign: '巨蟹 獅子' },
  'J:57/51|62/61': { zh: '並列交叉之直覺', en: 'The Juxtaposition Cross of Intuition', sign: '天秤' },
  'J:58/52|48/21': { zh: '並列交叉之活力*', en: 'The Juxtaposition Cross of Vitality', sign: '魔羯' },
  'J:59/55|16/9': { zh: '並列交叉之策略', en: 'The Juxtaposition Cross of Strategy', sign: '處女' },
  'J:6/36|15/10': { zh: '並列交叉之衝突', en: 'The Juxtaposition Cross of Conflict', sign: '處女' },
  'J:60/56|28/27': { zh: '並列交叉之限制', en: 'The Juxtaposition Cross of Limitation', sign: '魔羯 水瓶' },
  'J:61/62|50/3': { zh: '並列交叉之思考', en: 'The Juxtaposition Cross of Thinking', sign: '魔羯' },
  'J:62/61|3/50': { zh: '並列交叉之細節', en: 'The Juxtaposition Cross of Detail', sign: '巨蟹' },
  'J:63/64|26/45': { zh: '並列交叉之懷疑', en: 'The Juxtaposition Cross of Doubts', sign: '雙魚' },
  'J:64/63|45/26': { zh: '並列交叉之困惑', en: 'The Juxtaposition Cross of Confusion', sign: '處女' },
  'J:7/13|23/43': { zh: '並列交叉之相互影響*', en: 'The Juxtaposition Cross of Interaction', sign: '獅子' },
  'J:8/14|55/59': { zh: '並列交叉之貢獻', en: 'The Juxtaposition Cross of Contribution', sign: '金牛' },
  'J:9/16|64/63': { zh: '並列交叉之聚焦', en: 'The Juxtaposition Cross of Focus', sign: '射手' },
  'L:1/2|4/49': { zh: '左角度交叉之挑戰 2', en: 'The Left Angle Cross of Defiance 2', sign: '天蠍' },
  'L:10/15|18/17': { zh: '左角度交叉之預防 2', en: 'The Left Angle Cross of Prevention 2', sign: '射手 魔羯' },
  'L:11/12|46/25': { zh: '左角度交叉之教育 2', en: 'The Left Angle Cross of Education 2', sign: '射手' },
  'L:12/11|25/46': { zh: '左角度交叉之教育', en: 'The Left Angle Cross of Education', sign: '雙子' },
  'L:13/7|43/23': { zh: '左角度交叉之面具', en: 'The Left Angle Cross of Masks', sign: '水瓶' },
  'L:14/8|59/55': { zh: '左角度交叉之不確定 2', en: 'The Left Angle Cross of Uncertainty 2', sign: '天蠍' },
  'L:15/10|17/18': { zh: '左角度交叉之預防', en: 'The Left Angle Cross of Prevention', sign: '雙子 巨蟹' },
  'L:16/9|63/64': { zh: '左角度交叉之指認', en: 'The Left Angle Cross of Identification', sign: '雙子' },
  'L:17/18|38/39': { zh: '左角度交叉之動盪', en: 'The Left Angle Cross of Upheaval', sign: '牡羊' },
  'L:18/17|39/38': { zh: '左角度交叉之動盪 2', en: 'The Left Angle Cross of Upheaval 2', sign: '天秤' },
  'L:19/33|1/2': { zh: '左角度交叉之精緻* 2', en: 'The Left Angle Cross of Refinement 2', sign: '水瓶' },
  'L:2/1|49/4': { zh: '左角度交叉之挑戰', en: 'The Left Angle Cross of Defiance', sign: '金牛' },
  'L:20/34|37/40': { zh: '左角度交叉之二元性', en: 'The Left Angle Cross of Duality', sign: '雙子' },
  'L:21/48|54/53': { zh: '左角度交叉之努力*', en: 'The Left Angle Cross of Endeavour', sign: '牡羊' },
  'L:22/47|11/12': { zh: '左角度交叉之告知', en: 'The Left Angle Cross of Informing', sign: '雙魚' },
  'L:23/43|30/29': { zh: '左角度交叉之奉獻', en: 'The Left Angle Cross of Dedication', sign: '金牛' },
  'L:24/44|13/7': { zh: '左角度交叉之輪迴', en: 'The Left Angle Cross of Incarnation', sign: '金牛' },
  'L:25/46|58/52': { zh: '左角度交叉之療癒', en: 'The Left Angle Cross of Healing', sign: '雙魚 牡羊' },
  'L:26/45|6/36': { zh: '左角度交叉之衝突 2', en: 'The Left Angle Cross of Confrontation 2', sign: '射手' },
  'L:27/28|19/33': { zh: '左角度交叉之校準', en: 'The Left Angle Cross of Alignment', sign: '金牛' },
  'L:28/27|33/19': { zh: '左角度交叉之校準 2', en: 'The Left Angle Cross of Alignment 2', sign: '天蠍' },
  'L:29/30|20/34': { zh: '左角度交叉之勤奮* 2', en: 'The Left Angle Cross of Industry 2', sign: '獅子' },
  'L:3/50|41/31': { zh: '左角度交叉之希望', en: 'The Left Angle Cross of Wishes', sign: '牡羊 金牛' },
  'L:30/29|34/20': { zh: '左角度交叉之勤奮*', en: 'The Left Angle Cross of Industry', sign: '水瓶' },
  'L:31/41|24/44': { zh: '左角度交叉之創始', en: 'The Left Angle Cross of the Alpha', sign: '獅子' },
  'L:32/42|56/60': { zh: '左角度交叉之限制 2', en: 'The Left Angle Cross of Limitation 2', sign: '天秤' },
  'L:33/19|2/1': { zh: '左角度交叉之精緻*', en: 'The Left Angle Cross of Refinement', sign: '獅子' },
  'L:34/20|40/37': { zh: '左角度交叉之二元性 2', en: 'The Left Angle Cross of Duality 2', sign: '射手' },
  'L:35/5|22/47': { zh: '左角度交叉之分離', en: 'The Left Angle Cross of Separation', sign: '雙子' },
  'L:36/6|10/15': { zh: '左角度交叉之飛機* 2', en: 'The Left Angle Cross of the Plane 2', sign: '雙魚' },
  'L:37/40|5/35': { zh: '左角度交叉之遷移*', en: 'The Left Angle Cross of Migration', sign: '雙魚' },
  'L:38/39|57/51': { zh: '左角度交叉之個人主義 2', en: 'The Left Angle Cross of Individualism 2', sign: '魔羯' },
  'L:39/38|51/57': { zh: '左角度交叉之個人主義', en: 'The Left Angle Cross of Individualism', sign: '巨蟹' },
  'L:4/49|8/14': { zh: '左角度交叉之革命 2', en: 'The Left Angle Cross of Revolution 2', sign: '獅子' },
  'L:40/37|35/5': { zh: '左角度交叉之遷移* 2', en: 'The Left Angle Cross of Migration 2', sign: '處女' },
  'L:41/31|44/24': { zh: '左角度交叉之創始 2', en: 'The Left Angle Cross of the Alpha 2', sign: '水瓶' },
  'L:42/32|60/56': { zh: '左角度交叉之限制', en: 'The Left Angle Cross of Limitation', sign: '牡羊' },
  'L:43/23|29/30': { zh: '左角度交叉之奉獻 2', en: 'The Left Angle Cross of Dedication 2', sign: '天蠍' },
  'L:44/24|7/13': { zh: '左角度交叉之輪迴 2', en: 'The Left Angle Cross of Incarnation 2', sign: '天蠍' },
  'L:45/26|36/6': { zh: '左角度交叉之衝突', en: 'The Left Angle Cross of Confrontation', sign: '雙子' },
  'L:46/25|52/58': { zh: '左角度交叉之療癒 2', en: 'The Left Angle Cross of Healing 2', sign: '處女 天秤' },
  'L:47/22|12/11': { zh: '左角度交叉之告知 2', en: 'The Left Angle Cross of Informing 2', sign: '處女' },
  'L:48/21|53/54': { zh: '左角度交叉之努力* 2', en: 'The Left Angle Cross of Endeavour 2', sign: '天秤' },
  'L:49/4|14/8': { zh: '左角度交叉之革命', en: 'The Left Angle Cross of Revolution', sign: '水瓶' },
  'L:5/35|47/22': { zh: '左角度交叉之分離 2', en: 'The Left Angle Cross of Separation 2', sign: '射手' },
  'L:50/3|31/41': { zh: '左角度交叉之希望 2', en: 'The Left Angle Cross of Wishes 2', sign: '天秤 天蠍' },
  'L:51/57|61/62': { zh: '左角度交叉之號角', en: 'The Left Angle Cross of the Clarion', sign: '牡羊' },
  'L:52/58|21/48': { zh: '左角度交叉之要求', en: 'The Left Angle Cross of Demands', sign: '巨蟹' },
  'L:53/54|42/32': { zh: '左角度交叉之循環', en: 'The Left Angle Cross of Cycles', sign: '巨蟹' },
  'L:54/53|32/42': { zh: '左角度交叉之循環 2', en: 'The Left Angle Cross of Cycles 2', sign: '魔羯' },
  'L:55/59|9/16': { zh: '左角度交叉之靈魂', en: 'The Left Angle Cross of Spirit', sign: '雙魚' },
  'L:56/60|27/28': { zh: '左角度交叉之分心', en: 'The Left Angle Cross of Distraction', sign: '巨蟹 獅子' },
  'L:57/51|62/61': { zh: '左角度交叉之號角 2', en: 'The Left Angle Cross of the Clarion 2', sign: '天秤' },
  'L:58/52|48/21': { zh: '左角度交叉之要求 2', en: 'The Left Angle Cross of Demands 2', sign: '魔羯' },
  'L:59/55|16/9': { zh: '左角度交叉之靈魂 2', en: 'The Left Angle Cross of Spirit 2', sign: '處女' },
  'L:6/36|15/10': { zh: '左角度交叉之飛機* 2', en: 'The Left Angle Cross of the Plane 2', sign: '處女' },
  'L:60/56|28/27': { zh: '左角度交叉之分心 2', en: 'The Left Angle Cross of Distraction 2', sign: '魔羯 水瓶' },
  'L:61/62|50/3': { zh: '左角度交叉之朦朧 2', en: 'The Left Angle Cross of Obscuration 2', sign: '魔羯' },
  'L:62/61|3/50': { zh: '左角度交叉之朦朧', en: 'The Left Angle Cross of Obscuration', sign: '巨蟹' },
  'L:63/64|26/45': { zh: '左角度交叉之支配', en: 'The Left Angle Cross of Dominion', sign: '雙魚' },
  'L:64/63|45/26': { zh: '左角度交叉之支配 2', en: 'The Left Angle Cross of Dominion 2', sign: '處女' },
  'L:7/13|23/43': { zh: '左角度交叉之面具 2', en: 'The Left Angle Cross of Masks 2', sign: '獅子' },
  'L:8/14|55/59': { zh: '左角度交叉之不確定', en: 'The Left Angle Cross of Uncertainty', sign: '金牛' },
  'L:9/16|64/63': { zh: '左角度交叉之指認 2', en: 'The Left Angle Cross of Identification 2', sign: '射手' },
  'R:1/2|7/13': { zh: '右角度交叉之人面獅身 4', en: 'The Right Angle Cross of the Sphinx 4', sign: '天蠍' },
  'R:10/15|46/25': { zh: '右角度交叉之愛之船 4', en: 'The Right Angle Cross of Vessel of Love 4', sign: '射手 魔羯' },
  'R:11/12|6/36': { zh: '右角度交叉之伊甸園 4', en: 'The Right Angle Cross of Eden 4', sign: '射手' },
  'R:12/11|36/6': { zh: '右角度交叉之伊甸園 2', en: 'The Right Angle Cross of Eden 2', sign: '雙子' },
  'R:13/7|1/2': { zh: '右角度交叉之人面獅身', en: 'The Right Angle Cross of the Sphinx', sign: '水瓶' },
  'R:14/8|29/30': { zh: '右角度交叉之傳染 4', en: 'The Right Angle Cross of Contagion 4', sign: '天蠍' },
  'R:15/10|25/46': { zh: '右角度交叉之愛之船 2', en: 'The Right Angle Cross of Vessel of Love 2', sign: '雙子 巨蟹' },
  'R:16/9|37/40': { zh: '右角度交叉之計畫 2', en: 'The Right Angle Cross of Planning 2', sign: '雙子' },
  'R:17/18|58/52': { zh: '右角度交叉之服務', en: 'The Right Angle Cross of Service', sign: '牡羊' },
  'R:18/17|52/58': { zh: '右角度交叉之服務 3', en: 'The Right Angle Cross of Service 3', sign: '天秤' },
  'R:19/33|44/24': { zh: '右角度交叉之四方之路 4', en: 'The Right Angle Cross of the Four Ways 4', sign: '水瓶' },
  'R:2/1|13/7': { zh: '右角度交叉之人面獅身 2', en: 'The Right Angle Cross of the Sphinx 2', sign: '金牛' },
  'R:20/34|55/59': { zh: '右角度交叉之沉睡的鳳凰 2', en: 'The Right Angle Cross of the Sleeping Phoenix 2', sign: '雙子' },
  'R:21/48|38/39': { zh: '右角度交叉之張力', en: 'The Right Angle Cross of Tension', sign: '牡羊' },
  'R:22/47|26/45': { zh: '右角度交叉之統領', en: 'The Right Angle Cross of Rulership', sign: '雙魚' },
  'R:23/43|49/4': { zh: '右角度交叉之解釋 2', en: 'The Right Angle Cross of Explanation 2', sign: '金牛' },
  'R:24/44|19/33': { zh: '右角度交叉之四方之路', en: 'The Right Angle Cross of the Four Ways', sign: '金牛' },
  'R:25/46|10/15': { zh: '右角度交叉之愛之船', en: 'The Right Angle Cross of Vessel of Love', sign: '雙魚 牡羊' },
  'R:26/45|47/22': { zh: '右角度交叉之統領 4', en: 'The Right Angle Cross of Rulership 4', sign: '射手' },
  'R:27/28|41/31': { zh: '右角度交叉之不預期', en: 'The Right Angle Cross of the Unexpected', sign: '金牛' },
  'R:28/27|31/41': { zh: '右角度交叉之不預期 3', en: 'The Right Angle Cross of the Unexpected 3', sign: '天蠍' },
  'R:29/30|8/14': { zh: '右角度交叉之傳染 3', en: 'The Right Angle Cross of Contagion 3', sign: '獅子' },
  'R:3/50|60/56': { zh: '右角度交叉之律法', en: 'The Right Angle Cross of Laws', sign: '牡羊 金牛' },
  'R:30/29|14/8': { zh: '右角度交叉之感染*', en: 'The Right Angle Cross of Contagion', sign: '水瓶' },
  'R:31/41|27/28': { zh: '右角度交叉之不預期 2', en: 'The Right Angle Cross of the Unexpected 2', sign: '獅子' },
  'R:32/42|62/61': { zh: '右角度交叉之馬雅 3', en: 'The Right Angle Cross of Maya 3', sign: '天秤' },
  'R:33/19|24/44': { zh: '右角度交叉之四方之路 2', en: 'The Right Angle Cross of the Four Ways 2', sign: '獅子' },
  'R:34/20|59/55': { zh: '右角度交叉之沉睡的鳳凰 4', en: 'The Right Angle Cross of the Sleeping Phoenix 4', sign: '射手' },
  'R:35/5|63/64': { zh: '右角度交叉之意識 2', en: 'The Right Angle Cross of Consciousness 2', sign: '雙子' },
  'R:36/6|11/12': { zh: '右角度交叉之伊甸園', en: 'The Right Angle Cross of Eden', sign: '雙魚' },
  'R:37/40|9/16': { zh: '右角度交叉之計畫', en: 'The Right Angle Cross of Planning', sign: '雙魚' },
  'R:38/39|48/21': { zh: '右角度交叉之張力 4', en: 'The Right Angle Cross of Tension 4', sign: '魔羯' },
  'R:39/38|21/48': { zh: '右角度交叉之張力 2', en: 'The Right Angle Cross of Tension 2', sign: '巨蟹' },
  'R:4/49|23/43': { zh: '右角度交叉之解釋 3', en: 'The Right Angle Cross of Explanation 3', sign: '獅子' },
  'R:40/37|16/9': { zh: '右角度交叉之計畫 3', en: 'The Right Angle Cross of Planning 3', sign: '處女' },
  'R:41/31|28/27': { zh: '右角度交叉之不預期 4', en: 'The Right Angle Cross of the Unexpected 4', sign: '水瓶' },
  'R:42/32|61/62': { zh: '右角度交叉之馬雅', en: 'The Right Angle Cross of Maya', sign: '牡羊' },
  'R:43/23|4/49': { zh: '右角度交叉之解釋 4', en: 'The Right Angle Cross of Explanation 4', sign: '天蠍' },
  'R:44/24|33/19': { zh: '右角度交叉之四方之路 3', en: 'The Right Angle Cross of the Four Ways 3', sign: '天蠍' },
  'R:45/26|22/47': { zh: '右角度交叉之統領 2', en: 'The Right Angle Cross of Rulership 2', sign: '雙子' },
  'R:46/25|15/10': { zh: '右角度交叉之愛之船 3', en: 'The Right Angle Cross of Vessel of Love 3', sign: '處女 天秤' },
  'R:47/22|45/26': { zh: '右角度交叉之統領 3', en: 'The Right Angle Cross of Rulership 3', sign: '處女' },
  'R:48/21|39/38': { zh: '右角度交叉之張力 3', en: 'The Right Angle Cross of Tension 3', sign: '天秤' },
  'R:49/4|43/23': { zh: '右角度交叉之解釋', en: 'The Right Angle Cross of Explanation', sign: '水瓶' },
  'R:5/35|64/63': { zh: '右角度交叉之意識 4', en: 'The Right Angle Cross of Consciousness 4', sign: '射手' },
  'R:50/3|56/60': { zh: '右角度交叉之律法 3', en: 'The Right Angle Cross of Laws 3', sign: '天秤 天蠍' },
  'R:51/57|54/53': { zh: '右角度交叉之滲透*', en: 'The Right Angle Cross of Penetration', sign: '牡羊' },
  'R:52/58|17/18': { zh: '右角度交叉之服務 2', en: 'The Right Angle Cross of Service 2', sign: '巨蟹' },
  'R:53/54|51/57': { zh: '右角度交叉之滲透* 2', en: 'The Right Angle Cross of Penetration 2', sign: '巨蟹' },
  'R:54/53|57/51': { zh: '右角度交叉之滲透* 4', en: 'The Right Angle Cross of Penetration 4', sign: '魔羯' },
  'R:55/59|34/20': { zh: '右角度交叉之沉睡的鳳凰', en: 'The Right Angle Cross of the Sleeping Phoenix', sign: '雙魚' },
  'R:56/60|3/50': { zh: '右角度交叉之律法 2', en: 'The Right Angle Cross of Laws 2', sign: '巨蟹 獅子' },
  'R:57/51|53/54': { zh: '右角度交叉之滲透* 3', en: 'The Right Angle Cross of Penetration 3', sign: '天秤' },
  'R:58/52|18/17': { zh: '右角度交叉之服務 4', en: 'The Right Angle Cross of Service 4', sign: '魔羯' },
  'R:59/55|20/34': { zh: '右角度交叉之沉睡的鳳凰 3', en: 'The Right Angle Cross of the Sleeping Phoenix 3', sign: '處女' },
  'R:6/36|12/11': { zh: '右角度交叉之伊甸園 3', en: 'The Right Angle Cross of Eden 3', sign: '處女' },
  'R:60/56|50/3': { zh: '右角度交叉之律法 4', en: 'The Right Angle Cross of Laws 4', sign: '魔羯 水瓶' },
  'R:61/62|32/42': { zh: '右角度交叉之馬雅 4', en: 'The Right Angle Cross of Maya 4', sign: '魔羯' },
  'R:62/61|42/32': { zh: '右角度交叉之馬雅 2', en: 'The Right Angle Cross of Maya 2', sign: '巨蟹' },
  'R:63/64|5/35': { zh: '右角度交叉之意識', en: 'The Right Angle Cross of Consciousness', sign: '雙魚' },
  'R:64/63|35/5': { zh: '右角度交叉之意識 3', en: 'The Right Angle Cross of Consciousness 3', sign: '處女' },
  'R:7/13|2/1': { zh: '右角度交叉之人面獅身 3', en: 'The Right Angle Cross of the Sphinx 3', sign: '獅子' },
  'R:8/14|30/29': { zh: '右角度交叉之傳染 2', en: 'The Right Angle Cross of Contagion 2', sign: '金牛' },
  'R:9/16|40/37': { zh: '右角度交叉之計畫 4', en: 'The Right Angle Cross of Planning 4', sign: '射手' },
};
module.exports = { CROSS_TABLE };