// cities.js — 出生地城市與時區對照
// 時區使用 IANA 名稱，Node 內建資料庫涵蓋歷史夏令時間規則
const CITIES = [
  // ── 台灣
  { group: '台灣', name: '台北市', tz: 'Asia/Taipei' },
  { group: '台灣', name: '新北市', tz: 'Asia/Taipei' },
  { group: '台灣', name: '基隆市', tz: 'Asia/Taipei' },
  { group: '台灣', name: '桃園市', tz: 'Asia/Taipei' },
  { group: '台灣', name: '新竹市', tz: 'Asia/Taipei' },
  { group: '台灣', name: '新竹縣', tz: 'Asia/Taipei' },
  { group: '台灣', name: '苗栗縣', tz: 'Asia/Taipei' },
  { group: '台灣', name: '台中市', tz: 'Asia/Taipei' },
  { group: '台灣', name: '彰化縣', tz: 'Asia/Taipei' },
  { group: '台灣', name: '南投縣', tz: 'Asia/Taipei' },
  { group: '台灣', name: '雲林縣', tz: 'Asia/Taipei' },
  { group: '台灣', name: '嘉義市', tz: 'Asia/Taipei' },
  { group: '台灣', name: '嘉義縣', tz: 'Asia/Taipei' },
  { group: '台灣', name: '台南市', tz: 'Asia/Taipei' },
  { group: '台灣', name: '高雄市', tz: 'Asia/Taipei' },
  { group: '台灣', name: '屏東縣', tz: 'Asia/Taipei' },
  { group: '台灣', name: '宜蘭縣', tz: 'Asia/Taipei' },
  { group: '台灣', name: '花蓮縣', tz: 'Asia/Taipei' },
  { group: '台灣', name: '台東縣', tz: 'Asia/Taipei' },
  { group: '台灣', name: '澎湖縣', tz: 'Asia/Taipei' },
  { group: '台灣', name: '金門縣', tz: 'Asia/Taipei' },
  { group: '台灣', name: '連江縣（馬祖）', tz: 'Asia/Taipei' },

  // ── 亞洲
  { group: '亞洲', name: '香港', tz: 'Asia/Hong_Kong' },
  { group: '亞洲', name: '澳門', tz: 'Asia/Macau' },
  { group: '亞洲', name: '北京', tz: 'Asia/Shanghai' },
  { group: '亞洲', name: '上海', tz: 'Asia/Shanghai' },
  { group: '亞洲', name: '廣州', tz: 'Asia/Shanghai' },
  { group: '亞洲', name: '深圳', tz: 'Asia/Shanghai' },
  { group: '亞洲', name: '成都', tz: 'Asia/Shanghai' },
  { group: '亞洲', name: '西安', tz: 'Asia/Shanghai' },
  { group: '亞洲', name: '哈爾濱', tz: 'Asia/Shanghai' },
  { group: '亞洲', name: '烏魯木齊', tz: 'Asia/Urumqi' },
  { group: '亞洲', name: '東京', tz: 'Asia/Tokyo' },
  { group: '亞洲', name: '大阪', tz: 'Asia/Tokyo' },
  { group: '亞洲', name: '首爾', tz: 'Asia/Seoul' },
  { group: '亞洲', name: '新加坡', tz: 'Asia/Singapore' },
  { group: '亞洲', name: '吉隆坡', tz: 'Asia/Kuala_Lumpur' },
  { group: '亞洲', name: '曼谷', tz: 'Asia/Bangkok' },
  { group: '亞洲', name: '胡志明市', tz: 'Asia/Ho_Chi_Minh' },
  { group: '亞洲', name: '河內', tz: 'Asia/Ho_Chi_Minh' },
  { group: '亞洲', name: '馬尼拉', tz: 'Asia/Manila' },
  { group: '亞洲', name: '雅加達', tz: 'Asia/Jakarta' },
  { group: '亞洲', name: '新德里', tz: 'Asia/Kolkata' },
  { group: '亞洲', name: '孟買', tz: 'Asia/Kolkata' },
  { group: '亞洲', name: '杜拜', tz: 'Asia/Dubai' },
  { group: '亞洲', name: '伊斯坦堡', tz: 'Europe/Istanbul' },
  { group: '亞洲', name: '特拉維夫', tz: 'Asia/Jerusalem' },
  { group: '亞洲', name: '烏蘭巴托', tz: 'Asia/Ulaanbaatar' },
  { group: '亞洲', name: '仰光', tz: 'Asia/Yangon' },
  { group: '亞洲', name: '金邊', tz: 'Asia/Phnom_Penh' },
  { group: '亞洲', name: '可倫坡', tz: 'Asia/Colombo' },
  { group: '亞洲', name: '加德滿都', tz: 'Asia/Kathmandu' },

  // ── 歐洲
  { group: '歐洲', name: '倫敦', tz: 'Europe/London' },
  { group: '歐洲', name: '曼徹斯特', tz: 'Europe/London' },
  { group: '歐洲', name: '都柏林', tz: 'Europe/Dublin' },
  { group: '歐洲', name: '巴黎', tz: 'Europe/Paris' },
  { group: '歐洲', name: '布魯塞爾', tz: 'Europe/Brussels' },
  { group: '歐洲', name: '阿姆斯特丹', tz: 'Europe/Amsterdam' },
  { group: '歐洲', name: '柏林', tz: 'Europe/Berlin' },
  { group: '歐洲', name: '慕尼黑', tz: 'Europe/Berlin' },
  { group: '歐洲', name: '法蘭克福', tz: 'Europe/Berlin' },
  { group: '歐洲', name: '蘇黎世', tz: 'Europe/Zurich' },
  { group: '歐洲', name: '維也納', tz: 'Europe/Vienna' },
  { group: '歐洲', name: '布拉格', tz: 'Europe/Prague' },
  { group: '歐洲', name: '華沙', tz: 'Europe/Warsaw' },
  { group: '歐洲', name: '羅馬', tz: 'Europe/Rome' },
  { group: '歐洲', name: '米蘭', tz: 'Europe/Rome' },
  { group: '歐洲', name: '馬德里', tz: 'Europe/Madrid' },
  { group: '歐洲', name: '巴塞隆納', tz: 'Europe/Madrid' },
  { group: '歐洲', name: '里斯本', tz: 'Europe/Lisbon' },
  { group: '歐洲', name: '雅典', tz: 'Europe/Athens' },
  { group: '歐洲', name: '斯德哥爾摩', tz: 'Europe/Stockholm' },
  { group: '歐洲', name: '奧斯陸', tz: 'Europe/Oslo' },
  { group: '歐洲', name: '哥本哈根', tz: 'Europe/Copenhagen' },
  { group: '歐洲', name: '赫爾辛基', tz: 'Europe/Helsinki' },
  { group: '歐洲', name: '莫斯科', tz: 'Europe/Moscow' },
  { group: '歐洲', name: '基輔', tz: 'Europe/Kyiv' },
  { group: '歐洲', name: '布達佩斯', tz: 'Europe/Budapest' },

  // ── 美洲
  { group: '美洲', name: '紐約', tz: 'America/New_York' },
  { group: '美洲', name: '波士頓', tz: 'America/New_York' },
  { group: '美洲', name: '華盛頓', tz: 'America/New_York' },
  { group: '美洲', name: '亞特蘭大', tz: 'America/New_York' },
  { group: '美洲', name: '邁阿密', tz: 'America/New_York' },
  { group: '美洲', name: '芝加哥', tz: 'America/Chicago' },
  { group: '美洲', name: '休士頓', tz: 'America/Chicago' },
  { group: '美洲', name: '達拉斯', tz: 'America/Chicago' },
  { group: '美洲', name: '丹佛', tz: 'America/Denver' },
  { group: '美洲', name: '鳳凰城', tz: 'America/Phoenix' },
  { group: '美洲', name: '洛杉磯', tz: 'America/Los_Angeles' },
  { group: '美洲', name: '舊金山', tz: 'America/Los_Angeles' },
  { group: '美洲', name: '西雅圖', tz: 'America/Los_Angeles' },
  { group: '美洲', name: '拉斯維加斯', tz: 'America/Los_Angeles' },
  { group: '美洲', name: '檀香山', tz: 'Pacific/Honolulu' },
  { group: '美洲', name: '安克拉治', tz: 'America/Anchorage' },
  { group: '美洲', name: '多倫多', tz: 'America/Toronto' },
  { group: '美洲', name: '溫哥華', tz: 'America/Vancouver' },
  { group: '美洲', name: '蒙特婁', tz: 'America/Toronto' },
  { group: '美洲', name: '墨西哥城', tz: 'America/Mexico_City' },
  { group: '美洲', name: '聖保羅', tz: 'America/Sao_Paulo' },
  { group: '美洲', name: '里約熱內盧', tz: 'America/Sao_Paulo' },
  { group: '美洲', name: '布宜諾斯艾利斯', tz: 'America/Argentina/Buenos_Aires' },
  { group: '美洲', name: '聖地牙哥（智利）', tz: 'America/Santiago' },
  { group: '美洲', name: '利馬', tz: 'America/Lima' },
  { group: '美洲', name: '波哥大', tz: 'America/Bogota' },

  // ── 大洋洲
  { group: '大洋洲', name: '雪梨', tz: 'Australia/Sydney' },
  { group: '大洋洲', name: '墨爾本', tz: 'Australia/Melbourne' },
  { group: '大洋洲', name: '布里斯本', tz: 'Australia/Brisbane' },
  { group: '大洋洲', name: '伯斯', tz: 'Australia/Perth' },
  { group: '大洋洲', name: '阿德雷德', tz: 'Australia/Adelaide' },
  { group: '大洋洲', name: '奧克蘭', tz: 'Pacific/Auckland' },
  { group: '大洋洲', name: '威靈頓', tz: 'Pacific/Auckland' },

  // ── 非洲
  { group: '非洲', name: '開羅', tz: 'Africa/Cairo' },
  { group: '非洲', name: '約翰尼斯堡', tz: 'Africa/Johannesburg' },
  { group: '非洲', name: '開普敦', tz: 'Africa/Johannesburg' },
  { group: '非洲', name: '奈洛比', tz: 'Africa/Nairobi' },
  { group: '非洲', name: '拉哥斯', tz: 'Africa/Lagos' },
  { group: '非洲', name: '卡薩布蘭卡', tz: 'Africa/Casablanca' },
];

const CITY_GROUPS = ['台灣', '亞洲', '歐洲', '美洲', '大洋洲', '非洲'];

module.exports = { CITIES, CITY_GROUPS };
