// cross-table.js — 192個輪迴交叉中英文對照與完整說明（《區分的科學》譯名）
// 鍵格式: '角度代碼:個性太陽/個性地球|設計太陽/設計地球'  R=右角度 J=並列 L=左角度
// desc：輪迴交叉本身的固定說明文字（非個人化生成，來源同上）
const CROSS_TABLE = {
  'J:1/2|4/49': { zh: '並列交叉之自我表達', en: 'The Juxtaposition Cross of Self-Expression', sign: '天蠍', desc: '並列交叉自我表達：善於社交的人，能為人們尚未發問的問題，提供有創意、具革命性的解答。' },
  'J:10/15|18/17': { zh: '並列交叉之行為', en: 'The Juxtaposition Cross of Behavior', sign: '射手 魔羯', desc: '褒貶不一的機會主義者，期望自身的行為在別人心中留下好印象，同時又很快地管理或挑戰別人的行為。' },
  'J:11/12|46/25': { zh: '並列交叉之想法', en: 'The Juxtaposition Cross of Ideas', sign: '射手', desc: '本身帶有強大的突變子，收集各種普世的概念可能會成為重要的導師（或先知），往往堅守特定的看法或走向。' },
  'J:12/11|25/46': { zh: '並列交叉之發聲*', en: 'The Juxtaposition Cross of Articulation', sign: '雙子', desc: '傑出的演說者或老師，擁有罕見而令人印象深刻的天賦，能夠用自己聲音的音調變化，影響他人，使他人活出其個體性。' },
  'J:13/7|43/23': { zh: '並列交叉之傾聽', en: 'The Juxtaposition Cross of Listening', sign: '水瓶', desc: '很棒的傾聽者與守密者，擅用藝術的形式，來詮釋自己與突破性的洞見。' },
  'J:14/8|59/55': { zh: '並列交叉之激勵*', en: 'The Juxtaposition Cross of Empowering', sign: '天蠍', desc: '他們多愁善感的靈魂與其財務上穩固與否，緊密相連，握有資源來創造堅固的基礎，確保投資有所回報，激勵他人。' },
  'J:15/10|17/18': { zh: '並列交叉之極端', en: 'The Juxtaposition Cross of Extremes', sign: '雙子 巨蟹', desc: '這些人固守自己的韻律（通常是極端的韻律），與他人的韻律截然不同；他們並未察覺，自己天生能聚焦於需要被修正的事物上。' },
  'J:16/9|63/64': { zh: '並列交叉之實驗', en: 'The Juxtaposition Cross of Experimentation', sign: '雙子', desc: '有影響力的人，擅長運用自己的人際網絡，引發人們熱情來支持全新的實驗。' },
  'J:17/18|38/39': { zh: '並列交叉之意見', en: 'The Juxtaposition Cross of Opinions', sign: '牡羊', desc: '這些人總能以挑釁的方式，檢驗你的靈魂或使命；他們很容易分享許多意見，卻不見得容許別人與之爭辯。' },
  'J:18/17|39/38': { zh: '並列交叉之修正', en: 'The Juxtaposition Cross of Correction', sign: '天秤', desc: '擅長找出模式中的缺陷，除了自己之外，能辨認任何不適當的事物；有能力使麻雀變鳳凰。' },
  'J:19/33|1/2': { zh: '並列交叉之需要', en: 'The Juxtaposition Cross of Need', sign: '水瓶', desc: '創意導向，生命中對於創造與美感有深刻需求，而其親密的朋友圈為此受惠。' },
  'J:2/1|49/4': { zh: '並列交叉之駕駛*', en: 'The Juxtaposition Cross of the Driver', sign: '金牛', desc: '並列交叉駕駛：這些人完全專注於自己的方向，以及自己的駕駛原則，決定把別人拉進來同行。就算只跟他們短暫相處，也會改變你的方向。' },
  'J:20/34|37/40': { zh: '並列交叉之當下', en: 'The Juxtaposition Cross of the Now', sign: '雙子', desc: '為了部落、家族、伴侶及社群而忙；在社群自己想投注能量去做的事情中，不斷拔河。' },
  'J:21/48|54/53': { zh: '並列交叉之控制', en: 'The Juxtaposition Cross of Control', sign: '牡羊', desc: '內在對實現自我抱負，異常執著，向上提升的自我需求，他們需要全盤掌控，才能開始創新，創造全新的事物。' },
  'J:22/47|11/12': { zh: '並列交叉之優雅', en: 'The Juxtaposition Cross of Grace', sign: '雙魚', desc: '非常熱衷社交，能夠全神貫注地傾聽；他們是強而有力的突變媒介，能享受聆聽的藝術和樂趣。' },
  'J:23/43|30/29': { zh: '並列交叉之同化', en: 'The Juxtaposition Cross of Assimilation', sign: '金牛', desc: '有魅力的人，其任務是重複別人不熟悉的洞見，直到一切變得顯而易見，吸引願意聆聽的朋友，直到他們吸收了解為止。' },
  'J:24/44|13/7': { zh: '並列交叉之體悟', en: 'The Juxtaposition Cross of Rationalization', sign: '金牛', desc: '聰明、善於思考，有其固定的運作模式，以天生的邏輯和過往的經驗値，找到過去與未來的接續性，傳遞個人的覺知。' },
  'J:25/46|58/52': { zh: '並列交叉之天真', en: 'The Juxtaposition Cross of Innocence', sign: '雙魚 牡羊', desc: '專注於享受人生，說服你喜歡自己的本性，追求幸福。' },
  'J:26/45|6/36': { zh: '並列交叉之魔術', en: 'The Juxtaposition Cross of the Trickster', sign: '射手', desc: '天生具有行銷能力，能推銷給缺乏經驗的人，能推廣與眾不同的事物。' },
  'J:27/28|19/33': { zh: '並列交叉之照顧', en: 'The Juxtaposition Cross of Caring', sign: '金牛', desc: '總是不斷照顧每一個人，照顧每一件事，同時也懂得關懷自己，所有的記憶、突然的新發現與各種原則，都需要有其意義，才能成形。' },
  'J:28/27|33/19': { zh: '並列交叉之風險*', en: 'The Juxtaposition Cross of Risks', sign: '天蠍', desc: '勇於冒險的人，試圖超越極限，滿足其渴望，或是找到人生的目的與意義。' },
  'J:29/30|20/34': { zh: '並列交叉之承諾', en: 'The Juxtaposition Cross of Commitment', sign: '獅子', desc: '對其承諾，貫徹到底；他們是靈感的來源，像是將一生侍奉給神的聖人。' },
  'J:3/50|41/31': { zh: '並列交叉之突變', en: 'The Juxtaposition Cross of Mutation', sign: '牡羊 金牛', desc: '不斷尋找機會，改變不公平的法律，以便在突變的過程中，建立自己的定位與影響力。' },
  'J:30/29|34/20': { zh: '並列交叉之命運*', en: 'The Juxtaposition Cross of Fates', sign: '水瓶', desc: '精力充沛、堅持不懈，任由命運安排，基於完成渴望的執著與承諾，草莽行事。具備成為神秘學老師的潛能。' },
  'J:31/41|24/44': { zh: '並列交叉之影響', en: 'The Juxtaposition Cross of Influence', sign: '獅子', desc: '天生具備影響力與持續力，運用自己的思考過程、新的經驗、記憶，來說服別人。' },
  'J:32/42|56/60': { zh: '並列交叉之保存', en: 'The Juxtaposition Cross of Conservation', sign: '天秤', desc: '謹慎評估風險，如何存續與持久為其主要考慮，為確保未來世代生存無虞，保存資源。' },
  'J:33/19|2/1': { zh: '並列交叉之隱私*', en: 'The Juxtaposition Cross of Retreat', sign: '獅子', desc: '在生活中展現對美的需求；他們需要充足的食物和住所（自己的空間），才能展現隱居的美學。' },
  'J:34/20|40/37': { zh: '並列交叉之力量', en: 'The Juxtaposition Cross of Power', sign: '射手', desc: '忙碌於專注展現個人力量或魅力，以支持社群；他們是表演者或負責交易的業務經理。' },
  'J:35/5|22/47': { zh: '並列交叉之經驗', en: 'The Juxtaposition Cross of Experience', sign: '雙子', desc: '這些人的經驗能轉化為意識層面的提升，為人們帶來響；經驗就是一切。' },
  'J:36/6|10/15': { zh: '並列交叉之危機', en: 'The Juxtaposition Cross of Crisis', sign: '雙魚', desc: '懷抱對自己及人類的愛，擅長研究別人引發的危機行為，因而將（有關性方面的）經驗提升到更高的層次。' },
  'J:37/40|5/35': { zh: '並列交叉之交易', en: 'The Juxtaposition Cross of Bargains', sign: '雙魚', desc: '他們是無人能擋，熱力四射的談判者，擅長達成協議，發展社群。' },
  'J:38/39|57/51': { zh: '並列交叉之對抗', en: 'The Juxtaposition Cross of Opposition', sign: '魔羯', desc: '帶來興奮的能量，憑直覺挑釁、對抗（或驚嚇）別人，來證明並解釋自己的主張或看法。' },
  'J:39/38|51/57': { zh: '並列交叉之挑釁', en: 'The Juxtaposition Cross of Provocation', sign: '巨蟹', desc: '力量強大且情緒化，用驚嚇的方式去引發他人深層的潛能；他們明白自己的憂鬱，具有創造性的價値。' },
  'J:4/49|8/14': { zh: '並列交叉之公式', en: 'The Juxtaposition Cross of Formulization', sign: '獅子', desc: '帶來啟發，具備創造力，能建立公式並看到獨特的模，使新方向變得可行。' },
  'J:40/37|35/5': { zh: '並列交叉之拒絕', en: 'The Juxtaposition Cross of Denial', sign: '處女', desc: '其任務是擇善固執，拒絕協議，直到正確無誤為止，替社會快速的進展過程踩煞車。' },
  'J:41/31|44/24': { zh: '並列交叉之幻想', en: 'The Juxtaposition Cross of Fantasy', sign: '水瓶', desc: '有影響力的人，擅長看見趨勢，對未來懷抱夢想，因而獲得報酬；在虛擬的現實中，沈溺於幻想。' },
  'J:42/32|60/56': { zh: '並列交叉之完成', en: 'The Juxtaposition Cross of Completion', sign: '牡羊', desc: '這些人專注於完成他們所開始的事，就像馬拉松選手一樣，就算其他都已經回家了，他們也非要抵達終點才行。' },
  'J:43/23|29/30': { zh: '並列交叉之洞見', en: 'The Juxtaposition Cross of Insight', sign: '天蠍', desc: '並列交叉洞見：渴望傳達自己獨特的洞見，能有效影響那些已經準備好，願意聆聽的人。' },
  'J:44/24|7/13': { zh: '並列交叉之警覺', en: 'The Juxtaposition Cross of Alertness', sign: '天蠍', desc: '先知，具備警覺本能，知曉我們所經歷的過往，以及接下來即將邁向的未來，最好注意他們的存在。' },
  'J:45/26|36/6': { zh: '並列交叉之所有權*', en: 'The Juxtaposition Cross of Possession', sign: '雙子', desc: '有影響力的人，會為了社群，而接掌統治者的角色，在面臨危機或衝突時，能掌控一切。' },
  'J:46/25|52/58': { zh: '並列交叉之因緣俱足*', en: 'The Juxtaposition Cross of Serendipity', sign: '處女 天秤', desc: '這些人專注於讓自己在對的時間，出現在對的地點，他們了解正確的承諾（以及努力工作），能夠獲得財富和成功；完全享受活著的感覺。' },
  'J:47/22|12/11': { zh: '並列交叉之壓抑', en: 'The Juxtaposition Cross of Oppression', sign: '處女', desc: '運用對過去的了解，來推廣新的想法或概念，或以新觀念取代現有的認知。' },
  'J:48/21|53/54': { zh: '並列交叉之深度', en: 'The Juxtaposition Cross of Depth', sign: '天秤', desc: '有影響力的人，以他們的深度來拓展個人抱負，擴大朋友圈，讓自己有更多機會，能帶給人們衝擊、教導或幫助，使他人的不足得以蛻變，開創新事物。' },
  'J:49/4|14/8': { zh: '並列交叉之原則', en: 'The Juxtaposition Cross of Principles', sign: '水瓶', desc: '他們是革命家，行走於時代尖端，固守原則（通常與人權有關），為了要獲得強而有力的盟友，甚至願意與神交易。' },
  'J:5/35|47/22': { zh: '並列交叉之習慣', en: 'The Juxtaposition Cross of Habits', sign: '射手', desc: '有其既定的習慣與秩序，不容易被影響；具有固定的節奏，從中發展出習慣的模式或儀式，讓人生穩定運作。' },
  'J:50/3|31/41': { zh: '並列交叉之價值', en: 'The Juxtaposition Cross of Values', sign: '天秤 天蠍', desc: '有影響力的人，把握機會軟化或減輕法律的嚴苛，好確保罪責與罪行相當。' },
  'J:51/57|61/62': { zh: '並列交叉之驚嚇*', en: 'The Juxtaposition Cross of Shock', sign: '牡羊', desc: '他們以細節與自身直覺的洞見，帶來驚嚇，好讓人別過於嚴肅或自滿。' },
  'J:52/58|21/48': { zh: '並列交叉之靜止', en: 'The Juxtaposition Cross of Stillness', sign: '巨蟹', desc: '安靜愉悅地建立人際網絡；以潛在的深度或解決方法，創造機會，影響他人。' },
  'J:53/54|42/32': { zh: '並列交叉之開始', en: 'The Juxtaposition Cross of Beginnings', sign: '巨蟹', desc: '非常受歡迎的人，為蛻變的新循環、新開始灌注能量，評估成本、價値（社交能力），以及計劃的持續性。' },
  'J:54/53|32/42': { zh: '並列交叉之抱負*', en: 'The Juxtaposition Cross of Ambition', sign: '魔羯', desc: '並列交叉抱負：帶來蛻變的媒介，充滿響力卻又相對保守，被恐懼所驅動，需要完成自身的承諾，是一個永遠不會滿足的人。' },
  'J:55/59|9/16': { zh: '並列交叉之情緒', en: 'The Juxtaposition Cross of Moods', sign: '雙魚', desc: '並列交叉情緒：渴求深度、渴望知道眞理的人，他們的情緒穩定，具有強烈創造潛能；充滿創意的老師。' },
  'J:56/60|27/28': { zh: '並列交叉之刺激', en: 'The Juxtaposition Cross of Stimulation', sign: '巨蟹 獅子', desc: '為了讓生命有意義，他們願意冒險，追求更多刺激，他們是說故事的人，在訴說自己的故事時，得到釋放。' },
  'J:57/51|62/61': { zh: '並列交叉之直覺', en: 'The Juxtaposition Cross of Intuition', sign: '天秤', desc: '具有深刻的見解，並帶來啟發；他們運用自我的直覺、細節、理解和衝擊，讓人打開心防並接收訊息。' },
  'J:58/52|48/21': { zh: '並列交叉之活力*', en: 'The Juxtaposition Cross of Vitality', sign: '魔羯', desc: '這些人擁有令人嚮往的生命力及續航力，他們了解控制能量、以及如何分配的重要性，包括如何分配，以及分配給誰。' },
  'J:59/55|16/9': { zh: '並列交叉之策略', en: 'The Juxtaposition Cross of Strategy', sign: '處女', desc: '總是將焦點放在如何善用機會，制定策略，好與人親密。具備配對作媒的才能。' },
  'J:6/36|15/10': { zh: '並列交叉之衝突', en: 'The Juxtaposition Cross of Conflict', sign: '處女', desc: '抱持「順應生命」的態度，連結逝去的天眞，自危機中創造出最佳環境，讓陪伴、友誼與愛因而萌芽。' },
  'J:60/56|28/27': { zh: '並列交叉之限制', en: 'The Juxtaposition Cross of Limitation', sign: '魔羯 水瓶', desc: '足智多謀的人，能將隱藏於限制中的潛能發揮至極致；透過冒險來尋求人生的目的，同時滋養自己及他人，以測試每一種限制的界線。' },
  'J:61/62|50/3': { zh: '並列交叉之思考', en: 'The Juxtaposition Cross of Thinking', sign: '魔羯', desc: '並列交叉思考：聰明的人，熱愛追求知識，進入內在，鉅細靡遺深入其洞見，所具備的深度，足以改變既定的觀念，會是個好律師' },
  'J:62/61|3/50': { zh: '並列交叉之細節', en: 'The Juxtaposition Cross of Detail', sign: '巨蟹', desc: '擅長運用大量細節，來表達意見；若著眼於法律或製定法則時，他們會成為好律師。' },
  'J:63/64|26/45': { zh: '並列交叉之懷疑', en: 'The Juxtaposition Cross of Doubts', sign: '雙魚', desc: '聰明、令人信服，有影響力的懷疑論者，有能力說服他人，以邏輯性的解釋來平衡其體驗。' },
  'J:64/63|45/26': { zh: '並列交叉之困惑', en: 'The Juxtaposition Cross of Confusion', sign: '處女', desc: '鼓舞人心的歷史學家、資訊的泉源，他們的記憶源自於家族層級，並取決於自我的詮釋／操控。' },
  'J:7/13|23/43': { zh: '並列交叉之相互影響*', en: 'The Juxtaposition Cross of Interaction', sign: '獅子', desc: '不斷尋找各種方法，活出領導者的角色，散發影響力的同時，也避免自己被影響，而接受多元性，就成為他們領導的方式。' },
  'J:8/14|55/59': { zh: '並列交叉之貢獻', en: 'The Juxtaposition Cross of Contribution', sign: '金牛', desc: '以某種充滿創意又親密的方式，持續貢獻社會，像是結婚然後花許多年來翻修老舊房子。' },
  'J:9/16|64/63': { zh: '並列交叉之聚焦', en: 'The Juxtaposition Cross of Focus', sign: '射手', desc: '熱情激勵別人，引發眾人聚焦於社會的重要議題上，指認出未來社會的潛能，並為此灌注心力。' },
  'L:1/2|4/49': { zh: '左角度交叉之挑戰 2', en: 'The Left Angle Cross of Defiance 2', sign: '天蠍', desc: '吸引社會群體的個體人，此生是為了捍衛差異性；為了維護自身的獨特，強硬拒絕任何形式介入。' },
  'L:10/15|18/17': { zh: '左角度交叉之預防 2', en: 'The Left Angle Cross of Prevention 2', sign: '射手 魔羯', desc: '這些人似乎總是遇到行不通的事；這其實是一種天賦，能夠悉心指引社會，免於重蹈覆轍。' },
  'L:11/12|46/25': { zh: '左角度交叉之教育 2', en: 'The Left Angle Cross of Education 2', sign: '射手', desc: '「和平、博愛、傳播訊息」的人，渴望傳遞那些無法言喻的人類經驗。教育仍舊是人類的行為中最奧妙之處。' },
  'L:12/11|25/46': { zh: '左角度交叉之教育', en: 'The Left Angle Cross of Education', sign: '雙子', desc: '令人印象深刻的演講者，總是尋找優雅的聽眾；利用資源教育大眾，促進全球化的改變。' },
  'L:13/7|43/23': { zh: '左角度交叉之面具', en: 'The Left Angle Cross of Masks', sign: '水瓶', desc: '透過解釋或洞見，帶來轉化的潛能，以領導並指引他人，若能隱身於面具之後（像醫生那樣）效果最佳。' },
  'L:14/8|59/55': { zh: '左角度交叉之不確定 2', en: 'The Left Angle Cross of Uncertainty 2', sign: '天蠍', desc: '了解別人在財務上的不確定性，他們能夠提供別人所需，給予幫助；藉由提供（或應允或示範）物質層面的安全感，達到親密。' },
  'L:15/10|17/18': { zh: '左角度交叉之預防', en: 'The Left Angle Cross of Prevention', sign: '雙子 巨蟹', desc: '這些人似乎總是遇到行不通的事；這其實是一種天賦，能夠悉心指引社會，免於重蹈覆轍。' },
  'L:16/9|63/64': { zh: '左角度交叉之指認', en: 'The Left Angle Cross of Identification', sign: '雙子', desc: '強烈邏輯導向，有能力讓別人認同自己的技能或計劃，或認購其股票，因而得到支持、認購或投資。' },
  'L:17/18|38/39': { zh: '左角度交叉之動盪', en: 'The Left Angle Cross of Upheaval', sign: '牡羊', desc: '擅長按按鈕的人；總是攪亂現狀，為接下來的修正作準備，重新引導人們至健康的方向。' },
  'L:18/17|39/38': { zh: '左角度交叉之動盪 2', en: 'The Left Angle Cross of Upheaval 2', sign: '天秤', desc: '這些人帶有異端的思維或迷人的純真，總是蓄勢待發，試圖擾亂或挑戰行不通的一切；他們是治療師，知道治療的方法必須實際可行。' },
  'L:19/33|1/2': { zh: '左角度交叉之精緻* 2', en: 'The Left Angle Cross of Refinement 2', sign: '水瓶', desc: '這些人認為合宜的人生方向（共識）和偉大的美學息息相關，這不僅能滿足其需求，讓生命的經驗更盡善盡美，同時還能引領他們完成自身的使命。' },
  'L:2/1|49/4': { zh: '左角度交叉之挑戰', en: 'The Left Angle Cross of Defiance', sign: '金牛', desc: '這些人順著自己的方向走，但看起來總像在反抗一般社會的方向；他們具有讓別人脫離現況的能力。' },
  'L:20/34|37/40': { zh: '左角度交叉之二元性', en: 'The Left Angle Cross of Duality', sign: '雙子', desc: '忙碌並勤奮於工作，讓別人印象深刻，也讓自己獲得滿足；透過協議建造鏈接，營造互利共生的伙伴關係。' },
  'L:21/48|54/53': { zh: '左角度交叉之努力*', en: 'The Left Angle Cross of Endeavour', sign: '牡羊', desc: '有野心改變現狀的人，致力於將有深度的人聚集起來；渴望探索新的領域，以發展社群、商業及科學結構。' },
  'L:22/47|11/12': { zh: '左角度交叉之告知', en: 'The Left Angle Cross of Informing', sign: '雙魚', desc: '具備清晰表達的天賦，告知眾人嶄新而不同的事物，帶來突變。經由教導眾人新事物，引發突變。' },
  'L:23/43|30/29': { zh: '左角度交叉之奉獻', en: 'The Left Angle Cross of Dedication', sign: '金牛', desc: '有潛力的好老師，能夠一遍又一遍解釋同樣的事情，推動教育和改變；總是對接下來如何進展充滿興趣。' },
  'L:24/44|13/7': { zh: '左角度交叉之輪迴', en: 'The Left Angle Cross of Incarnation', sign: '金牛', desc: '這些人跟過去及未來有特別的連結，當他們和自己的人生軌道合一，就能為別人的方向帶來深刻的影響。' },
  'L:25/46|58/52': { zh: '左角度交叉之療癒', en: 'The Left Angle Cross of Healing', sign: '雙魚 牡羊', desc: '透過健康的身體，展現對生命的愛，專注感受生命的喜悅（品質），對於在不舒服中掙扎的人特別敏感，此生能透過「醫學」，來療癒別人或是療癒自己。' },
  'L:26/45|6/36': { zh: '左角度交叉之衝突 2', en: 'The Left Angle Cross of Confrontation 2', sign: '射手', desc: '優雅而有正義感，起身對抗權威，建立自己的統治地位；不願意輕易改變，擁有強大的自我。' },
  'L:27/28|19/33': { zh: '左角度交叉之校準', en: 'The Left Angle Cross of Alignment', sign: '金牛', desc: '懂得如何利用不預期的事物，帶來轉變，賦予適當的方向；幫助別人重新找到共識，並作出調整。' },
  'L:28/27|33/19': { zh: '左角度交叉之校準 2', en: 'The Left Angle Cross of Alignment 2', sign: '天蠍', desc: '懂得如何利用不預期的事物，帶來轉變，賦予適當的方向；幫助別人重新找到共識，並作出調整。' },
  'L:29/30|20/34': { zh: '左角度交叉之勤奮* 2', en: 'The Left Angle Cross of Industry 2', sign: '獅子', desc: '這些人沒有意識到自己強大的魅力，他們只要做出正確的承諾，就能堅持並發光。' },
  'L:3/50|41/31': { zh: '左角度交叉之希望', en: 'The Left Angle Cross of Wishes', sign: '牡羊 金牛', desc: '充滿吸引力與影響力的利他主義者，不斷尋找可能性，讓人們得以擁更好的生活；用全新的方式切入並帶來重整。' },
  'L:30/29|34/20': { zh: '左角度交叉之勤奮*', en: 'The Left Angle Cross of Industry', sign: '水瓶', desc: '活力充沛的人，非常忙碌地工作、創造與連結，以滿足他們內在渴望人類進步的動機：強烈渴望在每一個新的體驗中，感覺到各種情感的可能。' },
  'L:31/41|24/44': { zh: '左角度交叉之創始', en: 'The Left Angle Cross of the Alpha', sign: '獅子', desc: '強大的領導者，透過解決精神面的生存問題，影響他人；為了確保未來長治久安，不斷尋找實際的解決方案。' },
  'L:32/42|56/60': { zh: '左角度交叉之限制 2', en: 'The Left Angle Cross of Limitation 2', sign: '天秤', desc: '視無常為限制與壓力，就像公司與企業評估產品時，會以其實用性，及是否經得起時間考驗，主要的衡量標準。' },
  'L:33/19|2/1': { zh: '左角度交叉之精緻*', en: 'The Left Angle Cross of Refinement', sign: '獅子', desc: '這些人知道擁有並保護一個家，是不夠的；生命因為美麗的事物而豐富，美好的事物帶來療癒。' },
  'L:34/20|40/37': { zh: '左角度交叉之二元性 2', en: 'The Left Angle Cross of Duality 2', sign: '射手', desc: '在個人魅力／自私與群體責任間游移，為這兩種人性的基本難題，搭好橋樑；其忙碌與社群充滿愛 Support 的支持，緊密結合。' },
  'L:35/5|22/47': { zh: '左角度交叉之分離', en: 'The Left Angle Cross of Separation', sign: '雙子', desc: '在人生諸多經歷之後，獲得智慧，明白我們分以各自的方式，在社會中共同生活。由於各自對體驗有不同的詮釋方式，常常讓我們意見分歧，但這也是文明進化的過程。' },
  'L:36/6|10/15': { zh: '左角度交叉之飛機* 2', en: 'The Left Angle Cross of the Plane 2', sign: '雙魚', desc: '他們此生是為了享受自身的工作，同時吸引我們深入物質層面，在物質世界中得到生活所需，同時身處社會/物質世界之中，熱愛生活。' },
  'L:37/40|5/35': { zh: '左角度交叉之遷移*', en: 'The Left Angle Cross of Migration', sign: '雙魚', desc: '當共同的計劃或經驗已經完成，他們會另謀出路，征服下一個領域／經驗；他們是源頭，帶來進展。' },
  'L:38/39|57/51': { zh: '左角度交叉之個人主義 2', en: 'The Left Angle Cross of Individualism 2', sign: '魔羯', desc: '單純的人，他們必須不斷地突變／不斷成為自己，然後反過來驚嚇別人、製造緊張，或誘發別人內在的改變。' },
  'L:39/38|51/57': { zh: '左角度交叉之個人主義', en: 'The Left Angle Cross of Individualism', sign: '巨蟹', desc: '一股突變的力量，以其直覺的動見，與堅定的個人主義來撼動你，但本身並不容易受他人影響。' },
  'L:4/49|8/14': { zh: '左角度交叉之革命 2', en: 'The Left Angle Cross of Revolution 2', sign: '獅子', desc: '承接外在的投射，期待他們務實地，提出發起革命（或不發起革命）的理由，同時貢獻其資源。' },
  'L:40/37|35/5': { zh: '左角度交叉之遷移* 2', en: 'The Left Angle Cross of Migration 2', sign: '處女', desc: '總是在移動或搬遷的人，為下一個社群或村莊帶來進步、發展及改變。' },
  'L:41/31|44/24': { zh: '左角度交叉之創始 2', en: 'The Left Angle Cross of the Alpha 2', sign: '水瓶', desc: '並列交叉之幻想：有影響力的人，擅長看見趨勢，對未來懷抱夢想，因而獲得報酬；在虛擬的現實中，沈溺於幻想。' },
  'L:42/32|60/56': { zh: '左角度交叉之限制', en: 'The Left Angle Cross of Limitation', sign: '牡羊', desc: '知道事情是否可行的人，為了掌控資源，確保物質上的成功，他們了解接受限制是必要的，限制設立範疇，讓宇宙萬物得以相互依存。' },
  'L:43/23|29/30': { zh: '左角度交叉之奉獻 2', en: 'The Left Angle Cross of Dedication 2', sign: '天蠍', desc: '將洞見植入他人心中，引發微妙具順覆性的突變，使社會更有效率。' },
  'L:44/24|7/13': { zh: '左角度交叉之輪迴 2', en: 'The Left Angle Cross of Incarnation 2', sign: '天蠍', desc: '這些人不斷重溫過往，引領我們與過去連結，不斷思考何謂輪迴，以及如何生存。' },
  'L:45/26|36/6': { zh: '左角度交叉之衝突', en: 'The Left Angle Cross of Confrontation', sign: '雙子', desc: '在面臨危機和衝突時，支配家族資源的人，他們會站出來對抗或挑戰那些想掌控的人，堅持自己的要求。' },
  'L:46/25|52/58': { zh: '左角度交叉之療癒 2', en: 'The Left Angle Cross of Healing 2', sign: '處女 天秤', desc: '當他們與非關個人的宇宙之愛有所連結，會自然地療癒別人或是被療癒了；他們難能可貴，充滿喜悅的天賦，將透過專注、有承諾的連結，得以實現。' },
  'L:47/22|12/11': { zh: '左角度交叉之告知 2', en: 'The Left Angle Cross of Informing 2', sign: '處女', desc: '有社交技巧，擅長運用過往的經歷，啟發人心，轉移人們的注意力，看見那些被壓抑的人，所面對的困境，告知是一門藝術。' },
  'L:48/21|53/54': { zh: '左角度交叉之努力* 2', en: 'The Left Angle Cross of Endeavour 2', sign: '天秤', desc: '有野心改變現狀的人，致力於將有深度的人聚集起來；渴望探索新的領域，以發展社群、商業及科學結構。' },
  'L:49/4|14/8': { zh: '左角度交叉之革命', en: 'The Left Angle Cross of Revolution', sign: '水瓶', desc: '革命家，了解若人處飢餓中，和平不可得，認為擁有資源的人一定要分享給缺乏資源的人。' },
  'L:5/35|47/22': { zh: '左角度交叉之分離 2', en: 'The Left Angle Cross of Separation 2', sign: '射手', desc: '對愛開放，他們將自己和過去行不通的模式（或關係）分開來，試著理解過往，看見人生有更長遠的運作模式，領略其美麗，或帶來改變。' },
  'L:50/3|31/41': { zh: '左角度交叉之希望 2', en: 'The Left Angle Cross of Wishes 2', sign: '天秤 天蠍', desc: '超越傳統價値，具備理想主義的傾向，挑戰既定的文化與宗教準則，期待改變體系，找到不同作法的可能。' },
  'L:51/57|61/62': { zh: '左角度交叉之號角', en: 'The Left Angle Cross of the Clarion', sign: '牡羊', desc: '他們此生是為了驚嚇那些已經準備好覺醒的人，也就是那些對突變保持開放態度，能夠接受號角所帶來的靈感與直覺的洞見。' },
  'L:52/58|21/48': { zh: '左角度交叉之要求', en: 'The Left Angle Cross of Demands', sign: '巨蟹', desc: '為了使社會運作無虞，這些人要求找到解決辦法、完成修正，並且強制執行。' },
  'L:53/54|42/32': { zh: '左角度交叉之循環', en: 'The Left Angle Cross of Cycles', sign: '巨蟹', desc: '充滿野心，為了個體與國家（以及自己）助長蛻變性的改變發生。奉獻一己之力，完整並完成每個循環，讓一切延續。' },
  'L:54/53|32/42': { zh: '左角度交叉之循環 2', en: 'The Left Angle Cross of Cycles 2', sign: '魔羯', desc: '充滿野心，為了個體與國家（以及自己）助長蛻變性的改變發生。奉獻一己之力，完整並完成每個循環，讓一切延續。' },
  'L:55/59|9/16': { zh: '左角度交叉之靈魂', en: 'The Left Angle Cross of Spirit', sign: '雙魚', desc: '如果他們覺醒而察覺，性與愛情的課題，就能從生命和經驗中轉化，賦予他們智慧；透過靈性，轉化愛與性的關係。' },
  'L:56/60|27/28': { zh: '左角度交叉之分心', en: 'The Left Angle Cross of Distraction', sign: '巨蟹 獅子', desc: '以藝術的形式讓人分心，宛如魔術師般，能透過刺激和冒險的行事，超越限制。' },
  'L:57/51|62/61': { zh: '左角度交叉之號角 2', en: 'The Left Angle Cross of the Clarion 2', sign: '天秤', desc: '直覺敏銳，通常能帶來別人需要或想要的訊息，人們需要找到他們，要求指引。' },
  'L:58/52|48/21': { zh: '左角度交叉之要求 2', en: 'The Left Angle Cross of Demands 2', sign: '魔羯', desc: '如果能得到自己想要的回饋，這些人願意將自己的能量投注於別人的計劃，或是追求技能上的完美；最好的防守就是進攻。' },
  'L:59/55|16/9': { zh: '左角度交叉之靈魂 2', en: 'The Left Angle Cross of Spirit 2', sign: '處女', desc: '如果他們覺醒而察覺，性與愛情的課題，就能從生命和經驗中轉化，賦予他們智慧；透過靈性，轉化愛與性的關係。' },
  'L:6/36|15/10': { zh: '左角度交叉之飛機* 2', en: 'The Left Angle Cross of the Plane 2', sign: '處女', desc: '他們此生是為了享受自身的工作，同時吸引我們深入物質層面，在物質世界中得到生活所需，同時身處社會/物質世界之中，熱愛生活。' },
  'L:60/56|28/27': { zh: '左角度交叉之分心 2', en: 'The Left Angle Cross of Distraction 2', sign: '魔羯 水瓶', desc: '以藝術的形式讓人分心，宛如魔術師般，能透過刺激和冒險的行事，超越限制。' },
  'L:61/62|50/3': { zh: '左角度交叉之朦朧 2', en: 'The Left Angle Cross of Obscuration 2', sign: '魔羯', desc: '他們被啟發的覺知（來自內在眞理與宇宙法則的幽暗黑箱）能詳細道出絕對的普世法則，這些規則極容易被世人所忽略。' },
  'L:62/61|3/50': { zh: '左角度交叉之朦朧', en: 'The Left Angle Cross of Obscuration', sign: '巨蟹', desc: '這些人對於細節或統計的處理，能到達令人讚嘆或費解的地步。經過整理，原本晦澀難解的細節中，可能會帶來偉大的發現。' },
  'L:63/64|26/45': { zh: '左角度交叉之支配', en: 'The Left Angle Cross of Dominion', sign: '雙魚', desc: '在特定狀況下，他們強大的智慧充滿力量，足以掌控一切，有能力帶來質疑與困惑，以取得主權。' },
  'L:64/63|45/26': { zh: '左角度交叉之支配 2', en: 'The Left Angle Cross of Dominion 2', sign: '處女', desc: '詮釋過去，具有極大的影響力；運用資訊而位居要職或成為權威人士。' },
  'L:7/13|23/43': { zh: '左角度交叉之面具 2', en: 'The Left Angle Cross of Masks 2', sign: '獅子', desc: '承擔來自外在的投射，要他們提供實際或有智慧的領導方式，成為有影響力的改革推動者；他們最好躲在面具或頭銜背後來發揮影響力，像將軍或治療師。' },
  'L:8/14|55/59': { zh: '左角度交叉之不確定', en: 'The Left Angle Cross of Uncertainty', sign: '金牛', desc: '將能量轉化為實質形式，面對蛻變的不確定性，若要嘗試，需要秉持正確的精神與物質資源。' },
  'L:9/16|64/63': { zh: '左角度交叉之指認 2', en: 'The Left Angle Cross of Identification 2', sign: '射手', desc: '認知到自己渴望聚焦並發揮技能之所在（質疑或僵局），確保握有適當的資源可以解決問題，讓他們的心智穩定。' },
  'R:1/2|7/13': { zh: '右角度交叉之人面獅身 4', en: 'The Right Angle Cross of the Sphinx 4', sign: '天蠍', desc: '充滿創意的個體，以傳奇的方式彰顯自己的人生方向，使之永垂不朽；成為典範，提供並延續突變的方向。' },
  'R:10/15|46/25': { zh: '右角度交叉之愛之船 4', en: 'The Right Angle Cross of Vessel of Love 4', sign: '射手 魔羯', desc: '當他們全心投入於支持每個個體展現其獨特的行為，他們因而全然活出自己，愛自己的獨特之處，將世界往愛的方向推進。' },
  'R:11/12|6/36': { zh: '右角度交叉之伊甸園 4', en: 'The Right Angle Cross of Eden 4', sign: '射手', desc: '具有哲學性的思維，也許透過音樂與詩歌，來教導別人在這個世界上，關於體驗和情緒的本質。' },
  'R:12/11|36/6': { zh: '右角度交叉之伊甸園 2', en: 'The Right Angle Cross of Eden 2', sign: '雙子', desc: '善於表達，但固執己見的人，能將失去的純眞，化為藝術的形式；有其天賦，能以詩和音樂的形式，表達愛與危機。' },
  'R:13/7|1/2': { zh: '右角度交叉之人面獅身', en: 'The Right Angle Cross of the Sphinx', sign: '水瓶', desc: '具備個人方向，用自己獨特的方式記憶經驗，將鮮明而活躍的過去帶向未​​來。' },
  'R:14/8|29/30': { zh: '右角度交叉之傳染 4', en: 'The Right Angle Cross of Contagion 4', sign: '天蠍', desc: '透過財富與權力的持有與積累，承諾對社會有所貢獻；聰明運用資源，促進人類的成長、發展及進化。' },
  'R:15/10|25/46': { zh: '右角度交叉之愛之船 2', en: 'The Right Angle Cross of Vessel of Love 2', sign: '雙子 巨蟹', desc: '關心人類福祉是其天性，透過了解自己在事物發展過程中的定位，將多樣性帶入生命之流。' },
  'R:16/9|37/40': { zh: '右角度交叉之計畫 2', en: 'The Right Angle Cross of Planning 2', sign: '雙子', desc: '充滿熱忱，指示詳盡的解決辦法與正確的作為，找到有邏輯有條理的方式，展現並掌控進度。' },
  'R:17/18|58/52': { zh: '右角度交叉之服務', en: 'The Right Angle Cross of Service', sign: '牡羊', desc: '對於何謂為人處世，具備邏輯性的見解，化不滿足為驅動力，讓他們聚焦於修正、重整和服務人群。' },
  'R:18/17|52/58': { zh: '右角度交叉之服務 3', en: 'The Right Angle Cross of Service 3', sign: '天秤', desc: '不斷修正男/女和父／母的原型，使其趨於完美的過程；所有意見和修正都是為了服務人類，精益求精。' },
  'R:19/33|44/24': { zh: '右角度交叉之四方之路 4', en: 'The Right Angle Cross of the Four Ways 4', sign: '水瓶', desc: '對人權（或保育動物）等相關議題很敏感，因而備感壓力，深受社會及精神層面的力量所驅動，滿足別人的基本需求。' },
  'R:2/1|13/7': { zh: '右角度交叉之人面獅身 2', en: 'The Right Angle Cross of the Sphinx 2', sign: '金牛', desc: '具備影響力的密友，結合美學與人類的物質需求；在延續過去的同時，也改變整體物質世界的方向。' },
  'R:20/34|55/59': { zh: '右角度交叉之沉睡的鳳凰 2', en: 'The Right Angle Cross of the Sleeping Phoenix 2', sign: '雙子', desc: '充滿魅力，總是很忙；等待突變發生之前，他們會全神貫注把事情做好，或忙碌沉浸於自己的創造過程裡。' },
  'R:21/48|38/39': { zh: '右角度交叉之張力', en: 'The Right Angle Cross of Tension', sign: '牡羊', desc: '天生設立疆界的人，喜歡掌控自己的環境，與身處其中的人事物；他們擅於維持秩序，並監督情況。' },
  'R:22/47|26/45': { zh: '右角度交叉之統領', en: 'The Right Angle Cross of Rulership', sign: '雙魚', desc: '位居要位，懂得優雅地聽，天生具備統領的才能，最大的責任是教育王國裡的子民。當他們得以統禦人事物時，最為健康。' },
  'R:23/43|49/4': { zh: '右角度交叉之解釋 2', en: 'The Right Angle Cross of Explanation 2', sign: '金牛', desc: '永遠的局外人，他們總是在解釋自己，或解釋其獨特的概念、原則和洞見，以便整合至別人的革新或分析的過程裡。' },
  'R:24/44|19/33': { zh: '右角度交叉之四方之路', en: 'The Right Angle Cross of the Four Ways', sign: '金牛', desc: '這些人不斷重新審視「神是什麼？神在哪裡？誰是神？」等概念，渴望尋找明確的解答，使意識與形體能共同進化。' },
  'R:25/46|10/15': { zh: '右角度交叉之愛之船', en: 'The Right Angle Cross of Vessel of Love', sign: '雙魚 牡羊', desc: '覺知於更高層面的宇宙，超越個人的宇宙之愛，為人類未來的方向、求存的驅動力與繁衍物種之間，取得平衡。' },
  'R:26/45|47/22': { zh: '右角度交叉之統領 4', en: 'The Right Angle Cross of Rulership 4', sign: '射手', desc: '有社交魅力的人，巧妙挑選特定的記憶，加上人際之間的碰觸（握手、抱嬰兒），承諾教育每個人以改善未來，懂得營銷自己成為領導者，他們是今日的政治家。' },
  'R:27/28|41/31': { zh: '右角度交叉之不預期', en: 'The Right Angle Cross of the Unexpected', sign: '金牛', desc: '自然會被不預期的事物所引發，因而開啟一連串全新的體驗，因而滋養並擴展他們的智慧。' },
  'R:28/27|31/41': { zh: '右角度交叉之不預期 3', en: 'The Right Angle Cross of the Unexpected 3', sign: '天蠍', desc: '這些人總會不預期地承擔起責任，需要照顧某些人或某些事，當他們在掙扎中找到其中的意義，將成為具有影響力的典範。' },
  'R:29/30|8/14': { zh: '右角度交叉之傳染 3', en: 'The Right Angle Cross of Contagion 3', sign: '獅子', desc: '總是對新的（親密）的體驗說好，透過承諾尋求滿足感，他們能為體驗而體驗。' },
  'R:3/50|60/56': { zh: '右角度交叉之律法', en: 'The Right Angle Cross of Laws', sign: '牡羊 金牛', desc: '這些人塑造並改變我們的律法和價値觀，宛如藝術。我們的律法規範彼此如何共處，並為社會設立秩序。' },
  'R:30/29|14/8': { zh: '右角度交叉之感染*', en: 'The Right Angle Cross of Contagion', sign: '水瓶', desc: '天眞的命運實行者，透過體驗、發現和學習，走進別人的生命，並且不預期地改變他們的命運。' },
  'R:31/41|27/28': { zh: '右角度交叉之不預期 2', en: 'The Right Angle Cross of the Unexpected 2', sign: '獅子', desc: '天生有能力能吸引社會大眾的注意力，而成為不預期的領導者或英雄；往往就在不預期的狀態下，眾人會發掘並讚賞他們帶來滋養的影響力。' },
  'R:32/42|62/61': { zh: '右角度交叉之馬雅 3', en: 'The Right Angle Cross of Maya 3', sign: '天秤', desc: '這些人擁有內在覺知，並善用細節，造就其能力能評估並促進物質層面的成長、成熟及發展。' },
  'R:33/19|24/44': { zh: '右角度交叉之四方之路 2', en: 'The Right Angle Cross of the Four Ways 2', sign: '獅子', desc: '這些人在分享洞見、回憶或任何原則之前，需要單獨隱居，以思考並消化自己的經驗；他們需要獨處的隱私與空間。' },
  'R:34/20|59/55': { zh: '右角度交叉之沉睡的鳳凰 4', en: 'The Right Angle Cross of the Sleeping Phoenix 4', sign: '射手', desc: '具有強大個人力量與魅力，總是忙著以忙碌的樣子來吸引註意力；在靈魂層面的指引下所帶來的力量與親密​​，能服務眾人。' },
  'R:35/5|63/64': { zh: '右角度交叉之意識 2', en: 'The Right Angle Cross of Consciousness 2', sign: '雙子', desc: '具備經驗、熟悉一切的人，他們想要改變，也希望你能加入；隨時準備好探索全新的作法。' },
  'R:36/6|11/12': { zh: '右角度交叉之伊甸園', en: 'The Right Angle Cross of Eden', sign: '雙魚', desc: '缺乏經驗的人，追尋刺激或新的體驗，最終純真將逝去，取而代之的是智慧與優雅的展現。' },
  'R:37/40|9/16': { zh: '右角度交叉之計畫', en: 'The Right Angle Cross of Planning', sign: '雙魚', desc: '他們秉持自己的技能，與人交易，建立並維持社群的體制；透過相互連結，團結力量大，創造更好的成果。' },
  'R:38/39|48/21': { zh: '右角度交叉之張力 4', en: 'The Right Angle Cross of Tension 4', sign: '魔羯', desc: '這些人具有創造力與其深度，了解生命本身就是掙扎，但這掙扎是値得的，因為它能刺激靈性成長和使命的進展。' },
  'R:39/38|21/48': { zh: '右角度交叉之張力 2', en: 'The Right Angle Cross of Tension 2', sign: '巨蟹', desc: '這些人藉由激發別人的才能、領導力、使命和精神，將能量向外擴展，以釋放壓力；是擅長按按鈕的人。' },
  'R:4/49|23/43': { zh: '右角度交叉之解釋 3', en: 'The Right Angle Cross of Explanation 3', sign: '獅子', desc: '解釋革命性與原則性的解決方案，就是他們的工作，尚未經過測試的個人覺知，經由邏輯且公式化的檢驗，其洞見需要釐清，並且反覆說明。' },
  'R:40/37|16/9': { zh: '右角度交叉之計畫 3', en: 'The Right Angle Cross of Planning 3', sign: '處女', desc: '當所需的支持，與正確的協議皆到位，就能以自身的技能、邏輯的天賦，以及對細節的掌握，建立並滿足社群的需求。' },
  'R:41/31|28/27': { zh: '右角度交叉之不預期 4', en: 'The Right Angle Cross of the Unexpected 4', sign: '水瓶', desc: '不預期被推至領導地位，透過關懷或尋找人生目的，引領潮流並影響他人。' },
  'R:42/32|61/62': { zh: '右角度交叉之馬雅', en: 'The Right Angle Cross of Maya', sign: '牡羊', desc: '引領潮流的人，適當評估的細節，透過完成既定的循環，促進成長，為深具啟發性的全新啟點，做好鋪陳。' },
  'R:43/23|4/49': { zh: '右角度交叉之解釋 4', en: 'The Right Angle Cross of Explanation 4', sign: '天蠍', desc: '他們的覺知具有革命性；有效率又有邏輯地解釋自己革命性的洞見，奠定理解的基礎。' },
  'R:44/24|33/19': { zh: '右角度交叉之四方之路 3', en: 'The Right Angle Cross of the Four Ways 3', sign: '天蠍', desc: '這些家族人擁有敏銳的嗅覺、敏銳的本能、對歷史如數家珍，同時對他人的福祉極為敏感，不斷思考家族企業如何長久存續。' },
  'R:45/26|22/47': { zh: '右角度交叉之統領 2', en: 'The Right Angle Cross of Rulership 2', sign: '雙子', desc: '這些人來到世上，被賦予（或運作）權力，若以現代的話來說，他們就像是企業中的執行長。' },
  'R:46/25|15/10': { zh: '右角度交叉之愛之船 3', en: 'The Right Angle Cross of Vessel of Love 3', sign: '處女 天秤', desc: '身體力行，完全與其身體同步，能夠享受關係中的身體（感官）互動；為了生活本身，獻身於生活。' },
  'R:47/22|45/26': { zh: '右角度交叉之統領 3', en: 'The Right Angle Cross of Rulership 3', sign: '處女', desc: '位居要位，懂得優雅地聽，天生具備統領的才能，最大的責任是教育王國裡的子民。當他們得以統禦人事物時，最為健康。' },
  'R:48/21|39/38': { zh: '右角度交叉之張力 3', en: 'The Right Angle Cross of Tension 3', sign: '天秤', desc: '這些人具備內在深度，眞正了解問題所在，激發別人的技能、精神、意志，提供可行的解決方案。' },
  'R:49/4|43/23': { zh: '右角度交叉之解釋', en: 'The Right Angle Cross of Explanation', sign: '水瓶', desc: '四處遊歷的先知，為滿足生存所需，而指出必要的基本需求，並說明其中的必要原則；對於有所需求的人很敏感。' },
  'R:5/35|64/63': { zh: '右角度交叉之意識 4', en: 'The Right Angle Cross of Consciousness 4', sign: '射手', desc: '順應生命之流，進而產生成長與發展的動力；其意識與自然韻律相調和。' },
  'R:50/3|56/60': { zh: '右角度交叉之律法 3', en: 'The Right Angle Cross of Laws 3', sign: '天秤 天蠍', desc: '順應物種演化，他們創造、適應或評估法律及其價値，基於人類面對突變與改變時，求存的本能，將製訂法律視為充滿創意的內化歷程。' },
  'R:51/57|54/53': { zh: '右角度交叉之滲透*', en: 'The Right Angle Cross of Penetration', sign: '牡羊', desc: '這些人會在不經意間，以他們具滲透力的直覺洞見來吸引人們的注意力；他們的觀點出乎意料，總能帶來轉換，或為我們既定認知帶來突變。' },
  'R:52/58|17/18': { zh: '右角度交叉之服務 2', en: 'The Right Angle Cross of Service 2', sign: '巨蟹', desc: '有邏輯的人，肩負著責任（以及動能），確保我們採取正確的運作模式，走向未來。' },
  'R:53/54|51/57': { zh: '右角度交叉之滲透* 2', en: 'The Right Angle Cross of Penetration 2', sign: '巨蟹', desc: '在當下看起來似乎很快樂，試圖開始新事物來獲得認同，並為此感到壓力；他們能憑直覺而知道如何引發別人加入其行列。' },
  'R:54/53|57/51': { zh: '右角度交叉之滲透* 4', en: 'The Right Angle Cross of Penetration 4', sign: '魔羯', desc: '這些人在由貧致富的過程中，受到上位者的認同；向更高的力量（甚至是神秘力量）看齊。' },
  'R:55/59|34/20': { zh: '右角度交叉之沉睡的鳳凰', en: 'The Right Angle Cross of the Sleeping Phoenix', sign: '雙魚', desc: '充滿魅力，總是很忙；等待突變發生之前，他們會全神貫注把事情做好，或忙碌沉浸於自己的創造過程裡。' },
  'R:56/60|3/50': { zh: '右角度交叉之律法 2', en: 'The Right Angle Cross of Laws 2', sign: '巨蟹 獅子', desc: '懂得如何說故事，用理想主義的見解和信念，引發他人。他們的魔法與諸多承諾有關，是夢想家的夢想。' },
  'R:57/51|53/54': { zh: '右角度交叉之滲透* 3', en: 'The Right Angle Cross of Penetration 3', sign: '天秤', desc: '具備高度靈敏的直覺，能夠清晰看透世事；具有競爭優勢的清晰，能引領我們開拓新領域，緩和對未來的恐懼。' },
  'R:58/52|18/17': { zh: '右角度交叉之服務 4', en: 'The Right Angle Cross of Service 4', sign: '魔羯', desc: '由於生命充滿喜悅，如此奇妙，驅動他們勇於挑戰規範，透過服務社會的諸多理念和形式，讓一切井井有條運作無虞，漸趨完美。' },
  'R:59/55|20/34': { zh: '右角度交叉之沉睡的鳳凰 3', en: 'The Right Angle Cross of the Sleeping Phoenix 3', sign: '處女', desc: '強大的生育者，忙著「製造更多」以確保未來的安全；在連結中得到親密與安全感。' },
  'R:6/36|12/11': { zh: '右角度交叉之伊甸園 3', en: 'The Right Angle Cross of Eden 3', sign: '處女', desc: '運用衝突和危機中所得到的經驗，維持親密的人際連結；透過逝去的純眞，從中獲得經驗。' },
  'R:60/56|50/3': { zh: '右角度交叉之律法 4', en: 'The Right Angle Cross of Laws 4', sign: '魔羯 水瓶', desc: '這些人接受評估以及改變所衍生的枝節，皆有其限制，同時仍願意維持傳統價値，例如我們於法律中明文規定「人不該殺戮」。' },
  'R:61/62|32/42': { zh: '右角度交叉之馬雅 4', en: 'The Right Angle Cross of Maya 4', sign: '魔羯', desc: '啟發人（或被啟發）的思想家，他們須運用其頭腦來服務別人，如此才能避免自己因為無法得知的事物而惱怒；在事實和細節中尋找宇宙的眞理，解開生與死的課題。' },
  'R:62/61|42/32': { zh: '右角度交叉之馬雅 2', en: 'The Right Angle Cross of Maya 2', sign: '巨蟹', desc: '教育帶來強大的力量，他們知道邏輯可以帶來蛻變或療癒；運用創造力，以語言命名，描述那隱藏於細節之中，屬於內在的眞實，使之成形。' },
  'R:63/64|5/35': { zh: '右角度交叉之意識', en: 'The Right Angle Cross of Consciousness', sign: '雙魚', desc: '順應生命之流，進而產生成長與發展的動力；其意識與自然韻律相調和。' },
  'R:64/63|35/5': { zh: '右角度交叉之意識 3', en: 'The Right Angle Cross of Consciousness 3', sign: '處女', desc: '以過往經驗與既定模式相比，協助他人了解自己過往的模式，因而對人生產生全新的想法與理解。' },
  'R:7/13|2/1': { zh: '右角度交叉之人面獅身 3', en: 'The Right Angle Cross of the Sphinx 3', sign: '獅子', desc: '具備影響力與領導力，以清晰的邏輯看待過往，鑑往知來，引導人們走向安全的未來。' },
  'R:8/14|30/29': { zh: '右角度交叉之傳染 2', en: 'The Right Angle Cross of Contagion 2', sign: '金牛', desc: '以身作則，渴望貢獻，投入資源確保未來的安全及富裕；他們是能夠影響他人的進化楷模。' },
  'R:9/16|40/37': { zh: '右角度交叉之計畫 4', en: 'The Right Angle Cross of Planning 4', sign: '射手', desc: '充滿熱忱，實際專注於相關的細節。當所有面向都獲得審慎考量與充分支持，重大的事件（計畫、協議、才華）就能自然發展。' },
};

module.exports = { CROSS_TABLE };